steps:
  # 1. Build *and* push in the same command (needs BuildKit)
  - name: gcr.io/cloud-builders/docker
    env: ['DOCKER_BUILDKIT=1']
    args: [
      'buildx','build',
      '--platform=linux/amd64',
      '--push',                        # <-- pushes right away
      '-f','docker/images/n8n/Dockerfile',
      '-t','gcr.io/$PROJECT_ID/n8n:$SHORT_SHA',
      '.'
    ]

  # 2. Deploy only after the image is in the registry
  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    waitFor: ['-']                     # waits for every previous step
    args: [
      'run','deploy','n8n',
      '--image','gcr.io/$PROJECT_ID/n8n:$SHORT_SHA',
      '--region','us-central1',
      '--platform','managed',
      '--quiet'
    ]
