steps:
  - name: gcr.io/cloud-builders/docker
    env: ['DOCKER_BUILDKIT=1']          # BuildKit needed for the --mount lines :contentReference[oaicite:0]{index=0}
    # Build context is the repo root (.), but Dockerfile is in the sub-dir
    args: [
      'build',
      '-f', 'docker/images/n8n/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/n8n:$SHORT_SHA',
      '.'
    ]

  # (optional) deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run','deploy','n8n',
      '--image','gcr.io/$PROJECT_ID/n8n:$SHORT_SHA',
      '--region','us-central1','--platform','managed','--quiet'
    ]

images:
  - 'gcr.io/$PROJECT_ID/n8n:$SHORT_SHA'
